---
- name: User Setup
  hosts: all
  become: yes
  become_method: runas
  become_user: system

  tasks:
  - name: remove Development folder
    win_file:
      path: C:\Development
      state: absent

  - name: remove local user
    win_user:
      name: '{{item.name}}'
      state: absent
    with_items:
    - name: User1
    - name: User2

  - name: remove local group
    win_group:
      name: LocalGroup
      state: absent
...
