---
- name: IIS Deployment
  hosts: all
  become: yes
  become_method: runas
  become_user: system


  tasks:
  - name: Ensure IIS Server is present
    win_feature:
      name: Web-Server
      state: present
    register: iis_result

  - name: print iis_result
    debug:
      var: iis_result
    tags: debug

  - name: Is reboot required?
    debug:
      msg: "Host reboot is required. Notifying 'Reboot host' handler."
    when: iis_result.reboot_required == true
    notify: Reboot host

  - name: Ensure latest index.html file is present
    win_copy:
      content: "Hello World!"
      dest: c:\inetpub\wwwroot\index.html


  handlers:

  - name: Reboot host
    reboot:
    when: iis_result.reboot_required == true

...
