---
- name: IIS Removal
  hosts: all
  become: yes
  become_method: runas
  become_user: system


  tasks:

  - name: Remove index.html
    win_file:
      path: C:\inetpub\wwwroot\index.html
      state: absent

  - name: Disable IIS
    win_feature:
      name: Web-Server
      state: absent
    register: iis_result
    notify:
    - Reboot notification
    - Reboot host

  - name: print iis_result
    debug:
      var: iis_result
    tags: debug



  handlers:
          
  - name: Reboot notification
    debug: 
      msg: "Host reboot is required after removing IIS."
    when: iis_result.reboot_required == true

  - name: Reboot host
    win_reboot:
      test_command: whoami
    when: iis_result.reboot_required == true

...
