---
- name: Install Windows Packages
  hosts: windows
  fact_path: 'C:\scripts'

  tasks:

  - name: Install git
    win_chocolatey:
      name: git
      state: present

  - name: Remove notepad++
    win_chocolatey:
      name: notepadplusplus
      state: absent

  - name: Install notepad++ v7.1
    win_chocolatey:
      name: notepadplusplus
      version: '7.1'
      state: present

...

