---
- name: Install Windows Packages
  hosts: windows

  tasks:

  - name: Remove git
    win_chocolatey:
      name: git
      state: absent

  - name: Remove notepad++
    win_chocolatey:
      name: notepadplusplus
      state: absent

...

