---
- name: This is my Windows patching playbook
  hosts: all
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names: "{{ categories }}"
        reboot: "{{ reboot_server | defaults(yes) }}"

