---
- name: Register systems with Red Hat
  hosts: linux
  become: true
  vars:
    grub_ipv6_disable: 'ipv6.disable=1'

  tasks:

  - name: Disable cloud-init
    file:
      path: /etc/cloud/cloud-init.disabled
      state: touch

  ### Disable IPv6 ###
  # https://access.redhat.com/solutions/8709

  - name: Disable IPv6 built-in kernel module
    replace:
      path: /etc/default/grub
      regex: '^GRUB_CMDLINE_LINUX="(.*)"$'
      replace: 'GRUB_CMDLINE_LINUX="\1 {{ grub_ipv6_disable }}"'
      backup: true

  - name: Register RHEL Subscription
    redhat_subscription:
      state: present
      username: "{{ rhel_user }}"
      password: "{{ rhel_pass }}"
      auto_attach: true

  - name: Attach subscription
    shell: subscription-manager attach --auto
    register: attach_out

  - name: Debug - Attach subscription
    debug:
      var: attach_out
    tags: debug

  - name: Enable Extras Repo
    shell: subscription-manager repos --enable=rhel-7-server-extras-rpms
    register: extras_out

  - name: Debug - Enable Extras Repo
    debug:
      var: extras_out
    tags: debug
...

