---
- name: Install Windows Packages
  hosts: windows
  fact_path: 'C:\scripts'

  tasks:

  - name: What is installed?
    win_shell: 'choco list --local-only'
    register: applist

  - name: 'Debug: choco-local-list'
    debug:
      var: applist
    tags: debug

  - name: Install git
    win_chocolatey:
      name: git
      state: present

  - name: Remove notepad++
    win_chocolatey:
      name: notepadplusplus
      state: absent
    when: applist.stdout is search("notepadplusplus")

  - name: Install notepad++ v7.1
    win_chocolatey:
      name: notepadplusplus
      version: '7.1'
      state: present

...

