---
- name: Register systems with Red Hat
  hosts: linux
  become: true

  tasks:

  - name: Register RHEL Subscription
    redhat_subscription:
      state: present
      username: "{{ rhel_user }}"
      password: "{{ rhel_pass }}"
      auto_attach: true

  - name: Attach subscription
    shell: subscription-manager attach --auto
    register: attach_out

  - name: Debug - Attach subscription
    debug:
      var: attach_out

  - name: Enable Extras Repo
    shell: subscription-manager repos --enable=rhel-7-server-extras-rpms
    register: extras_out

  - name: Debug - Enable Extras Repo
    debug:
      var: extras_out
...

