---
- name: Remove Windows Packages
  hosts: windows

  tasks:

  - name: Remove putty
    win_chocolatey:
      name: putty.portable
      state: absent

  - name: Remove notepad++
    win_chocolatey:
      name: notepadplusplus.install
      state: absent
...

