---
- name: IIS Removal
  hosts: windows
  become: yes
  become_method: runas
  become_user: system


  tasks:

  - name: Remove index.html
    win_file:
      path: C:\inetpub\wwwroot\index.html
      state: absent

  - name: Disable IIS
    win_feature:
      name: Web-Server
      state: absent
    register: iis_result
    notify:
    - reboot

  - name: print iis_result
    debug:
      var: iis_result
      verbosity: 2


  handlers:

  - name: Reboot notification
    debug:
      msg: "Host reboot is required after removing IIS."
    listen: reboot
    when: iis_result.reboot_required

  - name: Reboot host
    win_reboot:
    listen: reboot
    when: iis_result.reboot_required

...
