---
# This playbook tests the script module on Windows hosts

- name: Powershell Script Demo
  hosts: all
  gather_facts: false

  tasks:

    - name: Running software_installed script
      script: files/software_installed_2.ps1
      register: output
      changed_when: output.rc
