---
- name: .Net - Use Strong Crypto
  hosts: windows
  gather_facts: false

  tasks:

  - name: Get Current Security Protocols
    win_shell: '[Net.ServicePointManager]::SecurityProtocol'
    register: securityprotocol
    changed_when: false

  - name: Print Security Protocols
    debug:
      msg: "Current security protocol settings: {{ securityprotocol.stdout_lines }}"

  - name: Set SchUseStrongCrypto in registry
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
      name: SchUseStrongCrypto
      type: dword
      data: 00000001
    when: securityprotocol.stdout_lines is search("Ssl3")

  - name: Reboot host
    win_reboot:

  - name: Get Current Security Protocols
    win_shell: '[Net.ServicePointManager]::SecurityProtocol'
    register: securityprotocol
    changed_when: false
     
  - name: Print Security Protocols
    debug:
      msg: "Current security protocol setting: {{ securityprotocol.stdout_lines }}"
  
...

