---
- name: Collect whoami info for default and become_user
  hosts: windows10
  gather_facts: no
  become_method: runas

  tasks:
  - name: default user
    win_shell: whoami

  - name: administrator
    become: yes
    become_user: system
    win_shell: whoami
...
